// core.js — deterministic math, hash, feature access (no Math.random anywhere)
'use strict';
const TAU = Math.PI * 2;

function clamp(v, a, b) { return v < a ? a : (v > b ? b : v); }
function lerp(a, b, t) { return a + (b - a) * t; }
function invLerp(a, b, v) { return b === a ? 0 : (v - a) / (b - a); }
function easeOut(x) { x = clamp(x, 0, 1); return 1 - Math.pow(1 - x, 3); }
function smooth(x) { x = clamp(x, 0, 1); return x * x * (3 - 2 * x); }

// stable hash over mixed numeric args -> uint32
function hash32() {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < arguments.length; i++) {
    let x = Math.imul(Math.round(arguments[i] * 1000) | 0, 374761393) >>> 0;
    h = (h ^ x) >>> 0;
    h = Math.imul(h ^ (h >>> 15), 2246822519) >>> 0;
    h = Math.imul(h ^ (h >>> 13), 3266489917) >>> 0;
  }
  return (h ^ (h >>> 16)) >>> 0;
}
function rnd01() { return hash32.apply(null, arguments) / 4294967296; }

// decaying impulse after event at t0
function decay(t, t0, tau) { return t < t0 ? 0 : Math.exp(-(t - t0) / tau); }

function fmtTime(s) {
  s = Math.max(0, s);
  const m = Math.floor(s / 60);
  const ss = s - m * 60;
  return String(m).padStart(2, '0') + ':' + ss.toFixed(2).padStart(5, '0');
}

// ---------- features (generated by tools/analyze.py) ----------
let FEAT = null;      // {rms, flux, wave, env: Int16Array, onsets: [[t,v]...]}
let BANDS = null;     // Int16Array nFrames * nBands

function initFeatures() {
  const toArr = (s) => Int16Array.from(s.split(','), Number);
  FEAT = {
    rms: toArr(FEATURES.rms),
    flux: toArr(FEATURES.flux),
    wave: toArr(FEATURES.wave),
    env: toArr(FEATURES.env),
    onsets: FEATURES.onsets,
  };
  const rows = FEATURES.bands.split(';');
  const n = FEATURES.nBands;
  BANDS = new Int16Array(rows.length * n);
  for (let i = 0; i < rows.length; i++) {
    const p = rows[i].split(',');
    for (let b = 0; b < n; b++) BANDS[i * n + b] = +p[b];
  }
}

function frameOf(t) {
  return clamp(Math.floor(t * FEATURES.fps), 0, FEATURES.nFrames - 1);
}

// summed onset impulses over the last 0.45s -> 0..1+
function onsetImpulse(t) {
  let s = 0;
  for (let i = 0; i < FEAT.onsets.length; i++) {
    const t0 = FEAT.onsets[i][0];
    if (t0 > t) break;
    const d = decay(t, t0, 0.13);
    if (d > 0.002) s += FEAT.onsets[i][1] * d;
  }
  return s;
}

function energy(t) { return FEAT.env[frameOf(t)] / 127; } // ~0..2

// ---------- timeline ----------
function sectionAt(t) {
  let s = SECTIONS[0];
  for (let i = 0; i < SECTIONS.length; i++) {
    if (SECTIONS[i].t <= t) s = SECTIONS[i]; else break;
  }
  return s;
}
function cueAt(t) {
  let c = null;
  for (let i = 0; i < CUES.length; i++) {
    if (CUES[i].t <= t) c = CUES[i]; else break;
  }
  return c;
}
function onsetsBetween(a, b) {
  let n = 0;
  for (let i = 0; i < FEAT.onsets.length; i++) {
    const t0 = FEAT.onsets[i][0];
    if (t0 >= a && t0 < b) n++;
    if (t0 >= b) break;
  }
  return n;
}
