#!/usr/bin/env python3
"""Precompute deterministic audio features for the MV renderer.

Output: data/features.js  (window.FEATURES = {...})
All values are integers so preview and export share identical data.
"""
import json, math, subprocess, sys, os

SR = 22050
HOP = 512
NFFT = 1024
FPS = 30
NBANDS = 16

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "song.flac")
OUT = os.path.join(ROOT, "data", "features.js")


def load_pcm(path):
    cmd = ["ffmpeg", "-v", "error", "-i", path, "-f", "f32le", "-ac", "1", "-ar", str(SR), "-"]
    raw = subprocess.run(cmd, capture_output=True, check=True).stdout
    import array
    a = array.array("f")
    a.frombytes(raw[: len(raw) - (len(raw) % 4)])
    return a


def main():
    import numpy as np

    pcm = np.asarray(load_pcm(SRC), dtype=np.float32)
    dur = len(pcm) / SR
    n_frames = int(math.ceil(dur * FPS))

    # ---- STFT ----
    n_hops = 1 + (len(pcm) - NFFT) // HOP
    win = np.hanning(NFFT).astype(np.float32)
    idx = np.arange(NFFT)[None, :] + HOP * np.arange(n_hops)[:, None]
    frames = pcm[idx] * win
    spec = np.fft.rfft(frames, axis=1)
    mag = np.abs(spec).astype(np.float32)
    freqs = np.fft.rfftfreq(NFFT, 1.0 / SR)

    # ---- onset strength: spectral flux (half-wave rectified) ----
    logmag = np.log1p(mag * 100.0)
    flux = np.diff(logmag, axis=0, prepend=logmag[:1])
    flux = np.maximum(flux, 0.0).sum(axis=1)
    flux /= (flux.max() + 1e-9)

    # ---- onset peaks ----
    hop_t = HOP / SR
    peaks = []
    min_gap = 0.13
    last = -1e9
    for i in range(1, len(flux) - 1):
        t = i * hop_t
        v = flux[i]
        if v > 0.16 and flux[i] >= flux[i - 1] and flux[i] >= flux[i + 1] and t - last >= min_gap:
            peaks.append((round(t, 3), round(float(v), 3)))
            last = t

    # ---- log bands ----
    fmin, fmax = 40.0, 10000.0
    edges = np.geomspace(fmin, fmax, NBANDS + 1)
    band_idx = []
    for b in range(NBANDS):
        m = (freqs >= edges[b]) & (freqs < edges[b + 1])
        band_idx.append(np.where(m)[0])
    band_idx = [bi if len(bi) > 0 else np.array([b]) for b, bi in enumerate(band_idx)]

    # ---- per-video-frame features ----
    rms = np.zeros(n_frames, dtype=np.float32)
    bands = np.zeros((n_frames, NBANDS), dtype=np.float32)
    ons = np.zeros(n_frames, dtype=np.float32)

    hop_frames = max(1, int(round(SR * hop_t / HOP)))  # ==1
    spec_frames_per_sec = SR / HOP
    for fi in range(n_frames):
        t = fi / FPS
        i0 = int(t * SR)
        i1 = min(len(pcm), i0 + int(SR / FPS))
        seg = pcm[i0:i1] if i1 > i0 else np.zeros(1, dtype=np.float32)
        rms[fi] = float(np.sqrt(np.mean(seg * seg) + 1e-12))
        si = min(int(t * spec_frames_per_sec), mag.shape[0] - 1)
        m = mag[si]
        for b in range(NBANDS):
            bands[fi, b] = float(m[band_idx[b]].mean())
        ons[fi] = flux[si]

    # ---- normalize & quantize ----
    rms_n = rms / (np.percentile(rms, 99.5) + 1e-9)
    rms_q = np.clip(rms_n * 255, 0, 255).astype(int)

    bands_log = np.log1p(bands * 20.0)
    bmax = np.percentile(bands_log, 99) + 1e-9
    bands_q = np.clip(bands_log / bmax * 255, 0, 255).astype(int)

    ons_q = np.clip(ons * 255, 0, 255).astype(int)

    # ---- waveform peaks (for the transport waveform) ----
    n_wave = 720
    wave = np.zeros(n_wave, dtype=np.float32)
    step = len(pcm) // n_wave
    for i in range(n_wave):
        seg = pcm[i * step:(i + 1) * step]
        if len(seg):
            wave[i] = float(np.max(np.abs(seg)))
    wave = wave / (wave.max() + 1e-9)
    wave_q = np.clip(wave * 255, 0, 255).astype(int)

    # ---- overall energy sections (for long-range structure) ----
    env = rms_n.copy()

    data = {
        "fps": FPS,
        "duration": round(dur, 3),
        "nFrames": n_frames,
        "nBands": NBANDS,
        "rms": ",".join(map(str, rms_q.tolist())),
        "flux": ",".join(map(str, ons_q.tolist())),
        "bands": ";".join(",".join(map(str, row.tolist())) for row in bands_q),
        "wave": ",".join(map(str, wave_q.tolist())),
        "env": ",".join(map(str, np.clip(env * 127, 0, 255).astype(int).tolist())),
        "onsets": [[t, v] for t, v in peaks],
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// generated by tools/analyze.py — do not edit\n")
        f.write("window.FEATURES = ")
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")

    print(f"duration={dur:.3f}s frames={n_frames} onsets={len(peaks)} "
          f"size={os.path.getsize(OUT)//1024}KB")


if __name__ == "__main__":
    main()
