// tools/gen_words.js — 逐字时间轴：每个词的演唱起止时刻 → data/words.js
// 边界策略：按音节数比例给出候选位置，再吸附到最近的音频 onset（单调约束），无 onset 处回退比例值。
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

global.window = {};
eval(fs.readFileSync(path.join(ROOT, 'data', 'features.js'), 'utf8')); // window.FEATURES
eval(fs.readFileSync(path.join(ROOT, 'data', 'cues.js'), 'utf8'));      // window.CUES
const FEATURES = global.window.FEATURES;
const CUES = global.window.CUES;
const onsets = FEATURES.onsets.map((o) => o[0]);

const holdOf = (c) => clampN(0.8 + c.text.length * 0.09, 1.2, 4.2);
function clampN(v, a, b) { return v < a ? a : (v > b ? b : v); }

function syllables(w) {
  const m = w.toLowerCase().match(/[aeiouy]+/g);
  return m ? m.length : 1;
}

const out = {};
let stats = { lines: 0, words: 0, snapped: 0, fallback: 0 };
for (const c of CUES) {
  if (c.meta || /^[\u4e00-\u9fa5]/.test(c.text)) { out[c.i] = []; continue; }
  const hold = holdOf(c);
  const win = Math.min((c.end - c.t) * 0.92, hold * 0.8);
  const words = c.text.split(/[^\w'.\/;:-]+/).filter(Boolean);
  const totalSyl = words.reduce((s, w) => s + syllables(w), 0);

  // proportional boundaries
  const props = [c.t];
  let acc = 0;
  for (let i = 0; i < words.length - 1; i++) {
    acc += syllables(words[i]);
    props.push(c.t + (acc / totalSyl) * win);
  }
  const endT = c.t + win;

  // onset candidates within window
  const ons = onsets.filter((t0) => t0 > c.t + 0.02 && t0 < endT - 0.02);

  // greedy monotonic snap: each boundary -> nearest onset after previous
  const bounds = [c.t];
  let prev = c.t;
  for (let k = 1; k < words.length; k++) {
    const target = props[k];
    let best = null, bestD = Infinity;
    for (const o of ons) {
      if (o <= prev + 0.04) continue;
      const d = Math.abs(o - target);
      if (d < bestD && d < 0.6) { best = o; bestD = d; } // snap only within 600ms
    }
    if (best !== null) { bounds.push(best); prev = best; stats.snapped++; }
    else { bounds.push(Math.max(prev + 0.04, target)); prev = bounds[bounds.length - 1]; stats.fallback++; }
  }
  bounds.push(endT);

  out[c.i] = words.map((w, i) => [
    w,
    Math.round(bounds[i] * 1000) / 1000,
    Math.round(Math.min(bounds[i + 1], endT) * 1000) / 1000,
  ]);
  stats.lines++;
  stats.words += words.length;
}

fs.writeFileSync(path.join(ROOT, 'data', 'words.js'),
  '// generated by tools/words.js — word-level karaoke timeline (onset-snapped)\n' +
  'window.WORDS = ' + JSON.stringify(out) + ';\n');
console.log('words.js:', stats.lines, 'lines /', stats.words, 'words / snapped', stats.snapped,
  '/ fallback', stats.fallback,
  '/', (fs.statSync(path.join(ROOT, 'data', 'words.js')).size / 1024).toFixed(0) + 'KB');
