// Parse song.lrc -> data/cues.js (window.CUES + window.SECTIONS)
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const lrc = fs.readFileSync(path.join(ROOT, "song.lrc"), "utf8");
const DURATION = 211.906667;

const cues = [];
let n = 0;
for (const raw of lrc.split(/\r?\n/)) {
  const m = raw.match(/^\[(\d+):(\d+(?:\.\d+)?)\]\s*(.*)$/);
  if (!m) continue;
  const t = Math.round((parseInt(m[1], 10) * 60 + parseFloat(m[2])) * 1000) / 1000;
  const text = m[3].trim();
  if (!text) continue;
  cues.push({ i: n++, t, text });
}
if (cues.length === 0) throw new Error("no cues parsed");
for (let k = 1; k < cues.length; k++) {
  if (cues[k].t < cues[k - 1].t) throw new Error(`non-monotonic cue ${k}`);
}
cues.forEach((c, k) => {
  c.end = k + 1 < cues.length ? cues[k + 1].t : DURATION;
  // metadata lines (作曲/作词) stay as annotations, not commands
  c.meta = /^[\u4e00-\u9fa5]/.test(c.text) && /[:\uff1a]/.test(c.text);
});
if (cues[cues.length - 1].t > DURATION) throw new Error("last cue beyond duration");

const SECTIONS = [
  { id: "boot", name: "BOOT", t: 0.0 },
  { id: "world", name: "world.execute(me);", t: 13.89 },
  { id: "v1", name: "SETUP", t: 29.7 },
  { id: "pre1", name: "PRE-EXEC", t: 59.22 },
  { id: "v2", name: "RUNTIME", t: 74.04 },
  { id: "iso", name: "ISOLATION", t: 114.04 },
  { id: "gap", name: "WAIT()", t: 131.3 },
  { id: "storm", name: "EXECUTION-STORM", t: 147.0 },
  { id: "final", name: "RE-EXEC", t: 161.9 },
  { id: "love", name: "LO-O-OVE", t: 177.24 },
  { id: "lull", name: "IDLE", t: 191.5 },
  { id: "end", name: "EXIT", t: 205.81 },
];
for (const s of SECTIONS) {
  s.idx = cues.findIndex((c) => c.t >= s.t);
  if (s.idx < 0) s.idx = cues.length - 1;
}
for (let k = 0; k < SECTIONS.length; k++) {
  const next = SECTIONS[k + 1];
  SECTIONS[k].endT = next ? next.t : DURATION;
  SECTIONS[k].endIdx = next ? next.idx : cues.length;
}

const out = `// generated by tools/parse_lrc.js — do not edit
window.CUES = ${JSON.stringify(cues)};
window.SECTIONS = ${JSON.stringify(SECTIONS)};
window.DURATION = ${DURATION};
`;
fs.writeFileSync(path.join(ROOT, "data", "cues.js"), out);
console.log(`cues=${cues.length} sections=${SECTIONS.length} bytes=${out.length}`);
